/*
 * Copyright Pham Van Nhieu and has some source refer on internet
 */

INSERT INTO public.location(
	id, address, close_time, description, image_ad, image_card, image_description, latitude, longitude, open_time, title, district_id)
	VALUES (1, '1428 K153 Nguyễn Văn Thoại, An Hải Đông, Sơn Trà, Đà Nẵng 550000, Vietnam', '21:00:00', 'Bà Nà về đêm là một bản nhạc có đủ cung bậc cảm xúc, từ lãng mạn với khung cảnh làng Pháp lung linh đèn đêm hệt như cổ tích, đến sôi động và cuồng nhiệt với những hoạt động lần đầu tiên được triển khai như đốt lửa trại, biểu diễn nghệ thuật ngoài trời giữa không gian đêm huyền ảo se lạnh với lãng đãng hơi sương...', 'du-lich-da-nang-ba-ad.jpg', 'cau-vang-ba-na-hills_card.jpg', 'ba-na-hill-description.png', 16.055322, 108.241040, '08:00:00', 'Khu du lịch Bà Nà Hills Đà Nẵng', 6),
	       (2, 'Phường Minh An, Hội An, Quảng Nam, Vietnam', '21:00:00', 'Còn gì hơn một buổi chiều nắng đẹp, du lịch Hội An để cảm nhận chút bình yên lắng đọng, những ngôi nhà cổ kính rêu phong. Hội An, một thành phố hiếm hoi cho đến tận bây giờ vẫn còn gìn giữ những nét đẹp văn hóa lâu đời, từ những ngôi trăm tuổi cho đến nghệ thuật bài chòi, làm lồng đèn, gốm sứ,… Hội An cũng liên tiếp được bình chọn là một trong 10 thành phố du lịch quyến rũ nhất thế giới, cũng chính vì lý do này mà không ít người đều mong muốn đến thăm Hội An dù chỉ một lần', 'hoian_ad.jpg', 'hoian_card.jpg', 'hoian_des.jpg', 15.878120, 108.328247, '08:00:00', 'Phố cổ hội an', 6),
	       (3, 'số 81 đường Huyền Trân Công chúa, phường Hòa Hải, quận Ngũ Hành Sơn, thành phố Đà Nẵng', '21:00:00', 'Quần thể di tích danh thắng Ngũ Hành Sơn gồm 6 ngọn núi đá vôi: Thổ Sơn, Hỏa Sơn (gồm có Dương Hỏa Sơn và Âm Hỏa Sơn), Thủy Sơn, Mộc Sơn, Kim Sơn. Thêm vào đó, nơi đây còn có phong cảnh đẹp cùng nhiều hang động huyền bí như động Huyền Không, động Huyền Vi, động Vân Thông,… lôi cuốn du khách đến tham quan, du lịch.', 'ngu_hanh_son_ad.jpg', 'ngu_hanh_son_card.jpg', 'ngu_hanh_son_des.jpg', 16.003465, 108.264462, '06:00:00', 'Núi Ngũ Hành Sơn', 5),
		   (4, '367H+8R9, Đường Trần Hưng Đạo, An Hải, Sơn Trà, Đà Nẵng 550000, Vietnam', '22:00:00', 'Cầu tình yêu Đà Nẵng nằm ở phía Đông của sông Hàn, đường Trần Hưng Đạo, quận Sơn Trà, thành phố Đà Nẵng. Cây cầu có hình vòng cung, được đi vào hoạt động từ năm 2015. Cầu tình yêu nằm giữa cầu Rồng và cầu sông Hàn, vì vậy đứng từ đây, bạn có thể ngắm nhìn rất nhiều phong cảnh đẹp, nổi tiếng của thành phố.', 'cau-tinh-yeu-ad.jpg', 'cau-tinh-yeu-card.jpg', 'cau-tinh-yeu-des.jpg', 16.063241, 108.229684, '06:00:00', 'Cầu khóa tình yêu', 6),
		   (5, '46 Phan Thanh, Thanh Khê, tp Đà Nẵng', '21:30:00', 'Ở quận Thanh Khê, bánh xèo tôm nhảy Năm Hiền được người dân bình chọn là một trong những món ăn nên thử. Công thức pha bột độc đáo tạo nên vỏ bánh mỏng giòn và phần nhân bánh giá đỗ, tôm đất, hành, thịt bằm rất vừa miệng. Được gọi là tôm nhảy vì những con tôm tươi sống được bỏ vào chảo, nhảy tanh tách trên khuôn bánh xèo. Không chỉ ngon bởi nhân tôm, bạn còn có thể thử nhân thịt bò cũng hấp dẫn không kém.', 'banh_xeo_ad.jpg', 'banh_xeo_card.jpg', 'banh_xeo_des.jpg', 16.064665, 108.207965, '10:30:00', 'Bánh xèo tôm nhảy của Năm Hiền', 3),
		   (6, 'Số 469 Hoàng Diệu, Hải Châu, tp Đà Nẵng', '21:00:00', 'Khi kể đến những quán ăn vặt ngon ở Đà Nẵng thì không thể bỏ qua quán ốc hút Cây Bàng được. Đây là địa điểm ăn uống Đà Nẵng nổi tiếng, đáp ứng đầy đủ 3 yêu cầu “ngon - bổ - rẻ”, thu hút nhiều bạn teen và du khách ghé thăm. Các món ăn ở đây như: ốc gạo, ốc đinh, ốc hương, ốc bươu… với mức giá rất hợp lý.', 'oc_ad.jpg', 'oc_card.jpg', 'oc_des.jpg', 16.052836, 108.217732, '14:00:00', 'Ốc hút Cây Bàng', 1),
           (7, 'Gác 3 trung tâm Thương nghiệp Hùng Vương, phường Hải Châu 1, quận Hải Châu, T.p Đà Nẵng.', '19:30:00', 'Nơi đây được biết đến là một trung tâm thương mại, nơi mua sắm sầm uất nhất tại Đà Nẵng. Với đủ các loại hàng hóa phong phú từ phổ thông đến cao cấp như vải vóc, giày dép, trang sức, các loại đặc sản gắn liền với đặc trưng thành phổ biển như mực rim me, cá khô… các sản phẩm mỹ nghệ truyền thống được thiết kế vô cùng tinh sảo với màu sắc bắt mắt, đảm bảo du khách sẽ được ngắm nhìn thỏa thích và tha hồ lựa chọn.', 'cho_con_ad.jpg', 'cho_con_card.jpg', 'cho_con_des.jpg', 16.068244, 108.214879, '14:00:00', 'Chợ cồn Đà Nẵng', 1),
		   (8, 'Khu thương Mại Vĩnh Trung, 255-257 Hùng Vương, Phường Vĩnh Trung, Quận Thanh Khê, Thành phố Đà Nẵng', '22:00:00', 'BigC Đà Nẵng – Hệ thống siêu thị Big C hoạt động kinh doanh theo mô hình “Trung tâm thương mại” hay “Đại siêu thị”, là hình thức kinh doanh bán lẻ hiện đại đang được Tập đoàn Casino (Tập đoàn mẹ của siêu thị Big C) triển khai. Casino là một trong những tập đoàn bán lẻ hàng đầu thế giới, với hơn 200.000 nhân viên làm việc tại hơn 11.000 chi nhánh, tại Việt Nam, Thái Lan, Argentina, Uruguay, Brazil, Columbia, Pháp, Madagascar và Mauritius. Hiện tại, siêu thị Big C Việt Nam có tổng cộng 19 siêu thị Big C trên toàn quốc.', 'big_c_ad.jpg', 'big_c_card.jpg', 'big_c_des.jpg', 16.068244, 108.214879, '07:00:00', 'Big C Đà Nẵng', 1),
		   (9, '24 Đ. Trần Phú, Thạch Thang, Hải Châu, Đà Nẵng 550000, Vietnam', '17:00:00', 'Bảo tàng Đà Nẵng thành lập từ năm 1989, được xây dựng mới tại địa điểm số 24 Trần Phú (phường Thạch Thang, quận Hải Châu), trong khuôn viên Di tích Quốc gia đặc biệt Thành Điện Hải. Bảo tàng Đà Nẵng được đầu tư phương tiện trưng bày, thiết bị nghe nhìn và hệ thống chiếu sáng hiện đại. Đội ngũ thuyết minh, hướng dẫn khách tham quan được đào tạo khá bài bản. Bảo tàng Đà Nẵng chính thức khánh thành, mở cửa đón khách tham quan vào ngày 26 tháng 4 năm 2011.Không gian trưng bày với diện tích hơn 3000m2 gồm 3 tầng giới thiệu hơn 2.500 tư liệu, hình ảnh, hiện vật có giá trị về lịch sử, văn hóa của thành phố Đà Nẵng và vùng phụ cận; trong đó có hơn 1.900 hiện vật gốc được sưu tầm từ sau ngày giải phóng đến nay, đặc biệt có nhiều tư liệu hiện vật quý, lần đầu tiên ra mắt công chúng', 'bao_tang_ad.jpg', 'bao_tang_card.jpg', 'bao_tang_des.jpg', 16.077544, 108.222491, '07:00:00', 'Bảo Tàng Đà Nẵng', 1),
		   (10, '1 Phan Đăng Lưu, Hoà Cường Bắc, Hải Châu, Đà Nẵng, Vietnam', '22:00:00', 'Asia Park là tổ hợp khu vui chơi giải trí nổi tiếng nhất ở Đà Nẵng. Được biết đến là một trong các địa điểm du lịch ở Đà Nẵng nên đi nơi đây luôn thu hút du khách đến tham quan, vui chơi, đặc biệt là vào cuối tuần. Asia Park bao gồm công viên vui chơi giải trí ngoài trời, vòng quay mặt trời Sun Wheel và công viên văn hóa.Công viên giải trí ngoài trời mang đến cho bạn trải nghiệm thú vị với nhiều trò chơi đặc sắc. Nếu bạn là một fan của các trò mạo hiểm, bạn sẽ có cơ hội thỏa sức tham gia các trò chơi như tàu lượn siêu tốc, tàu điện trên cao, tháp rơi tự do,...', 'bao_tang_ad.jpg', 'bao_tang_card.jpg', 'bao_tang_des.jpg', 16.038351, 108.226675, '08:00:00', 'Công viên châu Á - Asia Park', 1);