spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GMIT
    username: gmit
    password: abc123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        #     ddl-auto: create
        #Format SQL
        format_sql: true
