spring:
  profiles:
    active: heroku
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:db/location.sql,
        classpath:db/category.sql,
        classpath:db/category_location.sql,
        classpath:db/users.sql

      mode: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB