spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${USER_NAME}
    password: ${PASSSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: create
        #Format SQL
        format_sql: true
